name: Scan GitHub Actions

on:
  pull_request:
    paths:
      - ".github/**"
  push:
    branches:
      - main
    paths:
      - ".github/**"
  schedule:
    - cron: "17 9 * * 1"
  workflow_dispatch:

permissions: {}

jobs:
  scan:
    if: ${{ github.event_name != 'schedule' || github.repository == 'tempoxyz/wallet-cli' }}
    uses: tempoxyz/gh-actions/.github/workflows/scan-github-actions.yml@d39baa2b43f5eba5d261c047521a4fbd56101129 # 2026-09-23T04-31-11Z-d39baa2b
    permissions:
      actions: read
      contents: read
      id-token: write
