name: Scan GitHub Actions

on:
  pull_request:
    paths:
      - ".github/**"
  push:
    branches:
      - main
    paths:
      - ".github/**"
  schedule:
    - cron: "17 9 * * 1"
  workflow_dispatch:

permissions: {}

jobs:
  scan:
    if: ${{ github.event_name != 'schedule' || github.repository == 'tempoxyz/wallet-cli' }}
    uses: tempoxyz/gh-actions/.github/workflows/scan-github-actions.yml@bd66336ead0e97e3939428f526dc61fb43db0996 # 2026-09-25T20-13-44Z-bd66336e
    permissions:
      actions: read
      contents: read
      id-token: write
